multiCluter: true

source:
  # consumer configuration
  consumer:
    topic: topic1
    groupId: topic-replicator
    bootstrapServers: localhost:9092
    resetStrategy: earliest
  # kafka client properties
  client:
    security.protocol: SASL_SSL
    sasl.mechanism: AWS_MSK_IAM
    sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
    sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
    

destination:
  # producer configuration
  producer:
    topic: topic2
    bootstrapServers: localhost:9092
  # kafka client properties
  client:
    security.protocol: SASL_SSL
    sasl.mechanism: AWS_MSK_IAM
    sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
    sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler