source:
  topic: topic1
  consumer:
    group.id: topic-replicator
    bootstrap.servers: localhost:9092
    auto.offset.reset: earliest
    properties: 
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler


destination:
  topic: topic2
  producer:
    bootstrap.servers: localhost:9092
    properties: 
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler