# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: 
  push:
    branches:
    - 'main'
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/goreleaser/goreleaser-cross
      options: --user 1001
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Build linux-amd64
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 1
      run: go build -C src -v -o target/kafka-topic-replicator-$GOOS-$GOARCH

    - name: Build linux-arm64
      env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 1
      run: CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ go build -C src -v -o target/kafka-topic-replicator-$GOOS-$GOARCH

    - name: Print all that will be released
      run: ls src/target

    # - name: Creating a release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "src/target/*"
