# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: 
  push:
    branches:
    - 'main'
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build linux-amd64
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 1
      run: echo $GOOS && echo $GOARCH go build -C src -v -o target/kafka-topic-replicator-$GOOS-$GOARCH

    - name: Get current directory
      run: echo "DIR=$(pwd)" >> "$GITHUB_ENV"

    - name: Get arm64 cross-compiler
      run: wget -P $DIR/cc https://musl.cc/aarch64-linux-musl-cross.tgz && tar -xvf $DIR/cc/aarch64-linux-musl-cross.tgz -C ~ 

    - name: Build linux-arm64
      env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 1
        CC: $DIR/cc/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
      run: go build -C src -v -o target/kafka-topic-replicator-$GOOS-$GOARCH

    - name: Print all that will be released
      run: ls src/target

    # - name: Creating a release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "src/target/*"
