# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get version
      run: echo "VERSION=$(cat src/version)" >> "$GITHUB_ENV"

    - name: Build darwin-amd64
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -v -C src -o target/kafka-topic-replicator-$VERSION-$GOOS-$GOARCH

    - name: Build darwin-arm64
      env:
        GOOS: darwin
        GOARCH: arm64
      run: go build -v -C src -o target/kafka-topic-replicator-$VERSION-$GOOS-$GOARCH

    - name: Build linux-amd64
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -v -C src -o target/kafka-topic-replicator-$VERSION-$GOOS-$GOARCH

    - name: Build linux-amd64
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -v -C src -o target/kafka-topic-replicator-$VERSION-$GOOS-$GOARCH

    - name: Creating a release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "src/target/*"
