# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: 
  push:
    branches:
    - "main"
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/goreleaser/goreleaser-cross:v1.21.1
      options: --user 1001
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Print path
      run: pwd && echo $GITHUB_WORKSPACE

    - name: Get go version
      id: go_versioning
      run: echo "version=$(go version | AWK '{print $3}')" >> $GITHUB_OUTPUT

    - name: Find go-build cache
      id: go_cache
      run: echo "dir=$(go env GOCACHE)" >> $GITHUB_OUTPUT

    - name: Get release version
      id: versioning
      run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT

    - name: Cache go build
      uses: actions/cache@v3
      with:
        path: ${{ steps.go_cache.outputs.dir }}
        key: ${{ runner.os }}-go_cache-${{ hashFiles('src/go.sum') }}-${{ steps.go_versioning.version }}

    - name: Build linux-amd64
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 1
      run: go build -C src -v -o target/kafka-topic-replicator-$GOOS-$GOARCH

    - name: Build linux-arm64
      env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 1
        CC: aarch64-linux-gnu-gcc
        CXX: aarch64-linux-gnu-g++
      run: go build -C src -v -o target/kafka-topic-replicator-$GOOS-$GOARCH

    - uses: actions/upload-artifact@v3
      with:
        name: executables
        path: src/target/
        if-no-files-found: error

  release:
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v3
      id: download
      with:
        name: executables

    - name: Creating a release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.download.outputs.download-path }}/*
        tag: ${{ needs.build.outputs.version }}

  package:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          Containerfile
          
    - uses: actions/download-artifact@v3
      id: download
      with:
        name: executables
    
    - name: List directory and contents
      run: pwd && ls

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: kafka-topic-replicator
        tags: ${{ needs.build.outputs.version }} latest
        archs: amd64,arm64
        platforms: linux
        build-args: |
          PATH_TO_EXECUTABLE=${{ steps.download.outputs.download-path }}
        containerfiles: |
          ./Containerfile

    - name: Push packages
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/duartesaraiva98
