# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: 
  push:
    branches:
    - "main"
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/goreleaser/goreleaser-cross
      options: --user 1001
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    steps:
    - uses: actions/checkout@v3

    - name: Print env
      run: env

    - name: Find version
      id: versioning
      run: echo "version=$(git describe --tags)" >> "$GITHUB_OUTPUT"

    - name: Build linux-amd64
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 1
      run: go build -C src -v -o target/kafka-topic-replicator-$GOOS-$GOARCH

    - name: Build linux-arm64
      env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 1
        CC: aarch64-linux-gnu-gcc
        CXX: aarch64-linux-gnu-g++
      run: go build -C src -v -o target/kafka-topic-replicator-$GOOS-$GOARCH

    - name: Cache executables
      id: cache-executables
      uses: actions/cache@v3
      with:
          path: ${{ env.GITHUB_WORKSPACE }}/src/target
          key: executables
    
    - name: Cache containerfile
      id: cache-containerfile
      uses: actions/cache@v3
      with:
          path: ${{ env.GITHUB_WORKSPACE }}/Containerfile
          key: containerfile

  release:
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: write
    steps:
    - name: Restore cached executables
      id: cache-executables-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.GITHUB_WORKSPACE }}/src/target
        key: executables

    - name: Creating a release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.GITHUB_WORKSPACE }}/src/target/*"
        tag: ${{ needs.build.outputs.version }}

  package:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Restore cached executables
      id: cache-executables-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.GITHUB_WORKSPACE }}/src/target
        key: executables

    - name: Restore cached containerfile
      id: cache-containerfile-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.GITHUB_WORKSPACE }}/Containerfile
        key: containerfile

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: kafka-topic-replicator
        tags: ${{ needs.build.outputs.version }} latest
        containerfiles: |
          .${{ env.GITHUB_WORKSPACE }}/Containerfile

    - name: Push packages
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/duartesaraiva98